\# ==========================
# Application
# ==========================
spring.application.name=FileParser
server.port=8090

# ==========================
# PostgreSQL
# ==========================
spring.datasource.url=jdbc:postgresql://localhost:5432/fileparserdb
spring.datasource.username=postgres
spring.datasource.password=1234

# ==========================
# JPA
# ==========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==========================
# Multipart
# ==========================
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# ==========================
# Logging
# ==========================
logging.level.root=INFO
logging.level.com.fileparser=DEBUG