spring.application.name=authentication-demo

spring.mongodb.uri=mongodb+srv://preetitewatia9467_auth:Tiger@cluster0.7c7csy3.mongodb.net/authentication_demo?retryWrites=true&w=majority&appName=Cluster0

spring.mongodb.database=authentication_demo